                                 #Estrutura de repetição for

b = int(input('Digite um número:')) #[N] RECEBE INPUT, INICIA DE 0 ATÉ O NÚMERO RECEBIDO PELO INPUT
for c in range(0, b+1):
    print(c)
print('fim')  

#--------------------------------------------------------------------------------------------------

n = int(input('Digite um número:'))
for c in range(0, n+1, 2):
    print(c)
print('fim') # [N] RECEBE INPUT, INICIA DE 0 ATÉ O NÚMERO RECEBIDO PULANDO DE DOIS EM 2


