


for c in range(0, 2):
    n = int(input('Digite um valor:')) # RECEBENDO UMA VALOR(INPUT) VÁRIAS VEZES
   
    print(n)
print('fim')


#----------------------------------------------------------------------------------

s = 0
for c in range(0, 2):
    n = int(input('Digite um valor:')) # RECEBENDO UMA VALOR(INPUT) VÁRIAS VEZES E SOMANDO
    s+= n
    print(n)
print('A soma dos valores é: {}'.format(s))